FROM ubuntu:18.04

ENV USER kaggleuser

ENV DEBIAN_FRONTEND=noninteractive \
HOME=/home/${USER}

#create the environment
RUN apt-get update --fix-missing && \ 
    apt-get -y upgrade --fix-missing && \
    apt-get -y install apt-transport-https && \ 
    apt-get -y install python3-dev  && \
    apt-get -y install python3-pip 

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools 


COPY ./requirements.txt /code/requirements.txt
RUN pip3 install -r /code/requirements.txt 
RUN pip3 install psycopg2-binary 


#install kaggle
RUN pip3 install kaggle

#install the key
COPY ./kaggle /home/${USER}/.kaggle/

#make directory for workdir 
RUN mkdir -p /home/${USER}/workdir

# Copy code (mounted in development)
COPY ./ /home/${USER}/workdir/

#shift to program workdir
WORKDIR /home/${USER}/workdir/
